### ISSUE TITLE
Can't bind to 'dataSource' since it isn't a known property of 'ejs-grid'.

### ISSUE THREAD

**Issue by kevinding0218** [syncfusion/ej2-ng-grids#15]
Hello, I am trying the 'ej2-ng-grids' and follow the documentation on [https://ej2.syncfusion.com/angular/documentation/grid/getting-started.html#configuring-system-js], I did every exact step but when I still have the error "**Can't bind to 'dataSource' since it isn't a known property of 'ejs-grid'**", and my component.html seems does not recognize 'ejs-grid' even though I imported the GridModule or GridAllModule in my component module. **I looked the code in this repository while found out the grid.component.ts is importing some stuff from '@syncfusion/ej2-ng-base' and '@syncfusion/ej2-grids'. I am not sure if that's the reason my page got failed because I only installed 'ejs-ng-grid'?** 
**edit 8/1/2018**: that should not be the reason as I found out when installed the ej2-ng-grid I have those reference in my package.
**edit 8/2/2018**: I checked the file inside "node_modules\@syncfusion\ej2-ng-grids\src\grid" and found out 
1. the grid.component.d.ts does not declare the selector name.
2. the grid.module.d.ts or grid-all.module.d.ts content is empty.
Maybe that's why it failed?
**edit 8/2/2018**: I tried to download the current repository individually and put it inside my project, then referred the GridModule/GridAllModule from there, it also does not work...This is so weird..

Here is my steps:
1. npm install @syncfusion/ej2-ng-grids --save
shows "@syncfusion/ej2-ng-grids": "^16.2.46" in my package.json
2. In my component module
import { GridModule, GridAllModule } from '@syncfusion/ej2-ng-grids';
Then
imports: [
    CommonModule,
    GridAllModule
    // GridModule  failed
],
declaration: [myComponent]
3. In myComponent.html, simply call 
<ejs-grid [dataSource]='data'>
                <e-columns>
                    <e-column field='OrderID' headerText='Order ID' textAlign='Right' width=90></e-column>
                    <e-column field='CustomerID' headerText='Customer ID' width=120></e-column>
                    <e-column field='Freight' headerText='Freight' textAlign='Right' format='C2' width=90></e-column>
                    <e-column field='OrderDate' headerText='Order Date' textAlign='Right' format='yMd' width=120></e-column>
                </e-columns>
</ejs-grid>

Please let me know if I miss anything...

**Comment by jvhariharan** [comment]
Hi Kevin,

Query: Hello, I am trying the 'ej2-ng-grids' and follow the documentation on [https://ej2.syncfusion.com/angular/documentation/grid/getting-started.html#configuring-system-js], I did every exact step but when I still have the error "**Can't bind to 'dataSource' since it isn't a known property of 'ejs-grid'**"

We have validated your query and we are suspect that you are not importing the GridModule in app.module.ts file. Please find the steps to create the Grid in Angular environment.

•	You can use Angular CLI to setup your Angular applications. To install Angular CLI use the following command.

`npm install -g @angular/cli `

•	Start a new Angular application using below Angular CLI command.

`ng new my-app
cd my-app`

•	To install Grid component, use the following command.

`npm install @syncfusion/ej2-ng-grids –save`

•	Import Grid module into Angular application(app.module.ts) from the package @syncfusion/ej2-ng-grids [src/app/app.module.ts].

`import { NgModule } from '@angular/core';
import { BrowserModule } from '@angular/platform-browser';
// import the GridModule for the Grid component
import { GridModule } from '@syncfusion/ej2-ng-grids';
import { AppComponent }  from './app.component';

@NgModule({
  //declaration of ej2-ng-grids module into NgModule
  imports:      [ BrowserModule, GridModule ],   //import Grid Module
  declarations: [ AppComponent ],
  bootstrap:    [ AppComponent ]
})
export class AppModule { }`

•	Combined CSS files are available in the Essential JS 2 package root folder. This can be referenced in [src/styles.css] using following code.

`@import '../node_modules/@syncfusion/ej2-ng-grids/styles/material.css';`

•	Modify the template in [src/app/app.component.ts] file to render the grid component. Add the Angular Grid by using <ejs-grid> selector in template section of the app.component.ts file.

•	Bind data for the Grid component by using dataSource property.

•	The Grid has an option to define columns as directives. In these column directives, we have properties to customize columns.

•	To create grid with additional features, inject the required modules. The following modules are used to extend grid's basic functionality.
o	PageService- Inject this provider to use paging feature.
o	SortService- Inject this provider to use sorting feature.
o	FilterService - Inject this provider to use filtering feature.
o	GroupService - Inject this provider to use grouping feature.

These modules should be injected into the providers section of root NgModule or component class.

We have prepared a simple sample based on your requirement.

Sample Link: http://www.syncfusion.com/downloads/support/directtrac/general/ze/Sample-GridStart597666359

Help Documentation: 

To run the sample, use the below commands.

1.	npm install.
2.	npm start.

Please get back to us if you need further assistance on this.

Regards,
Hariharan

**Comment by kevinding0218** [comment]
Thank you very much for your help and guide! It works for me now!
