### ISSUE TITLE
Auto increment Primary key

### ISSUE THREAD

**Issue by susandotmark** [syncfusion/ej2-ng-grids#20]
Identity column starts with zero every time, how can we set the increment value for the primary and identity column in ts

**Comment by ej2gridsamples** [comment]
Hi Susan,


While using IsIdentity for a column, it is necessary to handle the IsIdentity column value while inserting records to Grid. Please refer the code example below,

**Note**: _Data source will be handled the Auto incremented column. Otherwise we need to set the value for IsIdentity column like as follows._
`public ActionResult Insert(EditableOrder value)
        {
            
            var data = OrderRepository.GetAllRecords().Last();
            value.OrderID = ++data.OrderID;
            OrderRepository.Add(value);
            return Json(value, JsonRequestBehavior.AllowGet);
        }
`
So, when enabling the IsIdentity property for Auto incremented column then we should return the values along with the response which is generated the value for IsIdentity column


Regards,
Venkatesh A.
