### ISSUE TITLE
Refresh dataSource with "frozenColumn" attribute doesn't work.

### ISSUE THREAD

**Issue by j-nord** [syncfusion/ej2-ng-grids#9]
Hi,

we have a pager for the grid. When we change the page we refresh the dataSource from the server.  Without the attribute "frozenColumn" it works. the datasource refresh is displayed in the grid. With the attribute "frozenColumn" it doesn't work.

Regards
j-nord

**Comment by pavithra95subramaniam** [comment]
Hi Nord,   

We have analyzed your query and we have created a simple sample based on the given information, but we are not able to reproduce the reported issue(‘Refreshing Datasource doesn't work with frozen Columns’). Please refer the below sample link. 

Sample: http://www.syncfusion.com/downloads/support/directtrac/general/ze/NGMVC1216223229  
 
Could you please provide more information or replicate the issue in the above sample and send back to us so that we could able to sort out the cause of this issue and provide you a better solutions quickly? 

Regards, 
Pavithra S.
